import Head from "next/head"
import Navbar from "../components/Navbar"
import HomePage from "./homePage"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Design Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/awf.ico" />
      </Head>
      <Navbar />
      <HomePage />
    </div>
  )
}
