import Head from "next/head"
import Navbar from "../components/Navbar"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Design Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/awf.ico" />
      </Head>
      <Navbar />

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </div>
  )
}
